services:
  # Aplikasi Utama
  mahasiswa-asing-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mahasiswa-asing-app:dev
    container_name: mahasiswa-asing-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mahasiswa_asing_db
      - SPRING_DATASOURCE_USERNAME=mahasiswa_user
      - SPRING_DATASOURCE_PASSWORD=rahasia_database
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - CAMUNDA_CLIENT_ZEEBE_GRPC_ADDRESS=http://zeebe:26500
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST:-smtp.gmail.com}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT:-587}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-your@gmail.com}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-your_app_password}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:-true}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:-true}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - zeebe
    networks:
      - mahasiswa-asing-network
      - camunda-platform

  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: mahasiswa-asing-postgres
    environment:
      - POSTGRES_DB=mahasiswa_asing_db
      - POSTGRES_USER=mahasiswa_user
      - POSTGRES_PASSWORD=rahasia_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mahasiswa-asing-network

  # Camunda Zeebe (Updated to 8.7.7)
  zeebe:
    image: camunda/zeebe:8.7.7
    container_name: mahasiswa-asing-zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8088:8080"
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - zeebe:/usr/local/zeebe/data
    networks:
      - camunda-platform
    depends_on:
      - elasticsearch

  # Camunda Operate (Updated to 8.7.7)
  operate:
    image: camunda/operate:8.7.7
    container_name: mahasiswa-asing-operate
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=false
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O - -q 'http://localhost:9600/actuator/health/readiness'",
        ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - elasticsearch

  # Camunda Tasklist (Updated to 8.7.7)
  tasklist:
    image: camunda/tasklist:8.7.7
    container_name: mahasiswa-asing-tasklist
    ports:
      - "8082:8080"
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://zeebe:8080
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_CSRFPREVENTIONENABLED=false
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O - -q 'http://localhost:9600/actuator/health/readiness'",
        ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - elasticsearch

  # Camunda Connectors (Updated to 8.7.5)
  connectors:
    image: camunda/connectors-bundle:8.7.5
    container_name: mahasiswa-asing-connectors
    ports:
      - "8085:8080"
    environment:
      - CAMUNDA_CLIENT_MODE=self-managed
      - CAMUNDA_CLIENT_ZEEBE_GRPCADDRESS=http://zeebe:26500
      - OPERATE_CLIENT_BASEURL=http://operate:8080
      - OPERATE_CLIENT_PROFILE=simple
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    env_file: connector-secrets.txt
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - operate

  # Elasticsearch (Updated to 8.17.6)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: mahasiswa-asing-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200/_cat/health | grep -q green",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - camunda-platform

volumes:
  postgres-data:
  zeebe:
  elastic:

networks:
  mahasiswa-asing-network:
    driver: bridge
  camunda-platform:
    driver: bridge
