global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Tambahkan target Alertmanager jika digunakan
          # - alertmanager:9093

rule_files:
  # Tambahkan file aturan alert jika diperlukan
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "mahasiswa-asing"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["mahasiswa-asing-app:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["mahasiswa-asing-postgres:5432"]

  - job_name: "camunda"
    static_configs:
      - targets: ["mahasiswa-asing-camunda:26500"]

  # Tambahan konfigurasi untuk monitoring sistem
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
