# ===================================================
# APLIKASI & SERVER
# ===================================================
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: pendaftaran-mahasiswa-asing

  # ===================================================
  # KONFIGURASI FILE UPLOAD
  # ===================================================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # ===================================================
  # SPRING SECURITY & DEVTOOLS
  # ===================================================
  security:
    filter:
      order: 10
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          microsoft:
            client-id: ${MICROSOFT_CLIENT_ID}
            client-secret: ${MICROSOFT_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys

# ===================================================
# KONFIGURASI KUSTOM (STORAGE DIRECTORY)
# ===================================================
storage:
  base-dir: ./storage
  upload-dir: ./storage/uploads
  temp-dir: ./storage/temp
  archive-dir: ./storage/archive
  logs-dir: ./storage/logs

# ===================================================
# KONFIGURASI APLIKASI
# ===================================================
app:
  autostart:
    enabled: false
  dashboard:
    cache-duration: 3600
    max-historical-data: 12
  mfa:
    enabled: false
    methods:
      - EMAIL
      - TOTP
    totp:
      issuer: UniversitasGunadarma
    email:
      sender: noreply@gunadarma.ac.id

# ===================================================
# LOGGING
# ===================================================
logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[io.camunda.zeebe]": INFO
    "[io.camunda.zeebe.spring.client.configuration]": ERROR
    "[io.camunda.zeebe.client.impl.ZeebeCallCredentials]": ERROR
    "[org.hibernate.orm.deprecation]": ERROR

# ===================================================
# ACTUATOR
# ===================================================
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
          - info
          - loggers
          - threaddump
          - heapdump
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      access: unrestricted
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# ===================================================
# SPRINGDOC OPENAPI
# ===================================================
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true
